// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcx2Q0BYYQPk9j0hZWXSN07gu96HR4wjk',
    appId: '1:765501186546:web:a225c2a0e4c1c6eb42cb6b',
    messagingSenderId: '765501186546',
    projectId: 'containers-a4afc',
    authDomain: 'containers-a4afc.firebaseapp.com',
    storageBucket: 'containers-a4afc.appspot.com',
    measurementId: 'G-QVSN8YW5GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvY99WklUz2jBGD0528LPVno-ZlMynqg',
    appId: '1:765501186546:android:f7a25953e5b1037142cb6b',
    messagingSenderId: '765501186546',
    projectId: 'containers-a4afc',
    storageBucket: 'containers-a4afc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8MzvVmkcmdS_WU-uFSuFvTKyTDCZia0',
    appId: '1:765501186546:ios:795ecad4af81013742cb6b',
    messagingSenderId: '765501186546',
    projectId: 'containers-a4afc',
    storageBucket: 'containers-a4afc.appspot.com',
    iosBundleId: 'com.bakten.containers',
  );
}
